services:
  redis:
    image: redis:latest
    container_name: lnk-redis
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:latest
    container_name: lnk-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=lnk-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

  grafana:
    image: grafana/otel-lgtm:latest
    container_name: lnk-grafana
    ports:
      - "8081:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - cassandra
      - redis
