services:
  nginx:
    image: nginx:alpine
    container_name: lnk-nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - lnk-network

  app:
    build: .
    environment:
      - CASSANDRA_HOSTS=cassandra-lb:9042
      - REDIS_HOST=redis:6379
      - PORT=8080
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - lnk-network
    depends_on:
      - cassandra-lb
      - redis
    deploy:
      replicas: 4
    env_file:
      - .env

  cassandra-lb:
    image: haproxy:2.8-alpine
    container_name: lnk-cassandra-lb
    ports:
      - "9042:9042"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - cassandra
    networks:
      - lnk-network

  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=lnk-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - lnk-network

  redis:
    image: redis:latest
    container_name: lnk-redis
    ports:
      - "6379:6379"
    networks:
      - lnk-network

  grafana:
    image: grafana/otel-lgtm:latest
    container_name: lnk-grafana
    ports:
      - "8081:3000"
      - "4317:4317"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - lnk-network

volumes:
  cassandra-data:

networks:
  lnk-network:
    driver: bridge
